[package]
name = "prime"
version = "0.1.0"
edition = "2024"
description = "A CLI tool for prime number generation and checking"
license = "MIT OR Apache-2.0"

[dependencies]
anyhow = "1.0"
chrono = "0.4"
colored = "2.0"
dirs = "5.0"
lazy_static = "1.5.0"
regex = "1.10"
reqwest = { version = "0.11", features = ["blocking", "json"] }
rustyline = "12.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tempfile = "3.8"
